# Generated by Django 5.0.7 on 2024-08-16 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hold', 'Hold'), ('golden_cross', 'Golden Cross/Death Cross')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('params', models.JSONField(default=dict)),
                ('coin', models.ManyToManyField(to='strategy.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('ma', 'Moving Average'), ('ema', 'Exponential Moving Average')], max_length=20)),
                ('period', models.IntegerField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='strategy.strategy')),
            ],
        ),
    ]
